package com.ibm.posj;

public interface IBM4610PrinterCmdConst extends POSPrinterCmdConst {
   byte LEFT_TO_RIGHT_TOPLEFT = 0;
   byte BOTTOM_TO_TOP_BOTTOMLEFT = 1;
   byte RIGHT_TO_LEFT_BOTTOMRIGHT = 2;
   byte TOP_TO_BOTTOM_TOPRIGHT = 3;
   byte SLIP_FONTA = 0;
   byte SLIP_FONTB = 1;
   byte SLIP_PAGE2 = 2;
   byte SLIP_FONT_WIDTH = 7;
   byte SLIP_FONT_HEIGHT = 9;
   byte REC_FONTA = 0;
   byte REC_FONTB = 1;
   byte REC_FONTC = 2;
   byte REC_FONTA_WIDTH = 10;
   byte REC_FONTB_WIDTH = 12;
   byte REC_FONTC_WIDTH = 8;
   byte REC_FONTA_HEIGHT = 20;
   byte REC_FONTB_HEIGHT = 24;
   byte REC_FONTC_HEIGHT = 16;
   byte RESIDENT_CS = 0;
   byte NONRESIDENT_CS = 1;
   byte UDF_PAGE1 = 0;
   byte UDF_PAGE2 = 1;
   byte UDF_PAGE3 = 2;
   byte UDF_PAGE4 = 3;
   byte FM_IMPACT_CS = 3;
   byte FM_THERM_CS = 4;
   byte FM_DBCS = 6;
   byte DEFAULT_SPACING = 3;
   byte REC_DOT_MIN = 0;
   byte REC_DOT_MAX = 8;
   byte SLIP_DOT_MIN = 0;
   byte SLIP_DOT_MAX = 8;
   byte REC_DBCS_DOT_MIN = 0;
   byte REC_DBCS_DOT_MAX = 32;
   byte SLIP_DBCS_DOT_MIN = 0;
   byte SLIP_DBCS_DOT_MAX = 32;
   int ER_RELEASE_AFTER_CORRECTION = 1;
   int ER_AUTO_RETRY_AFTER_HOME_ERROR = 2;
   int ER_WAIT_FOR_DOCUMENT = 4;
   int ER_RELEASE_AFTER_FLIP_ERROR = 8;
   byte[][] FONT_TYPE_TABLE = new byte[][]{{2, 0, 10}, {2, 1, 12}, {2, 2, 8}, {4, 0, 7}, {4, 1, 7}};
   byte FLASH_SECTOR_EIGHT = 8;
}
