package com.ibm.posj;

public interface LineDisplayCmdConst {
   int CLEAR_DISPLAY_CMD_CODE = 400;
   int WRITE_DISPLAY_CMD_CODE = 401;
   int SET_CHARACTER_SET_CMD_CODE = 402;
   int WRITE_TRIANGLE_MARKS_CMD_CODE = 403;
   int TEST_REQUEST_CMD_CODE = 404;
   int STATUS_REQUEST_CMD_CODE = 405;
   int BRIGHTNESS_CMD_CODE = 406;
   int SCREEN_MODE_CMD_CODE = 407;
   int DISPLAY_MODE_CMD_CODE = 408;
   int CURSOR_MODE_CMD_CODE = 409;
   int USER_DEFINABLE_CHARACTER_CMD_CODE = 410;
   int DISPLAY_TEXT_MODE_CMD_CODE = 411;
   String CLEAR_DISPLAY_CMD_NAME = "CLEAR_DISPLAY";
   String WRITE_DISPLAY_CMD_NAME = "WRITE_DISPLAY";
   String SET_CHARACTER_SET_CMD_NAME = "SET_CHARACTER_SET";
   String WRITE_TRIANGLE_MARKS_CMD_NAME = "WRITE_TRIANGLE_MARKS";
   String TEST_REQUEST_CMD_NAME = "TEST_REQUEST_CMD";
   String STATUS_REQUEST_CMD_NAME = "STATUS_REQUEST_CMD";
   String BRIGHTNESS_CMD_NAME = "BRIGHTNESS_CMD";
   String SCREEN_MODE_CMD_NAME = "SCREEN_MODE_CMD";
   String DISPLAY_MODE_CMD_NAME = "DISPLAY_MODE_CMD";
   String CURSOR_MODE_CMD_NAME = "CURSOR_MODE_CMD";
   String USER_DEFINABLE_CHARACTER_CMD_NAME = "USER_DEFINABLE_CHARACTER_CMD";
   String DISPLAY_TEXT_MODE_CMD_NAME = "DISPLAY_TEXT_MODE_CMD";
   byte DISP_CHAR_SPACE = 32;
   byte DISP_CHAR_CARRIAGE_RETURN = 13;
   byte DISP_CHAR_LINE_FEED = 10;
   int DISP_LENGTH_DATA = 20;
   int DISP_LENGTH_INDICATORS = 4;
   byte DISP_DEF_CUR_LOCATION = 0;
}
