package com.ibm.posj;

public interface ScaleHandleConst {
   int CLEAR_DISPLAY_SCALE_CMD_CODE = 1100;
   int CONFIG_SCALE_CMD_CODE = 1101;
   int ENABLE_EXTENDED_STATUS_CMD_CODE = 1102;
   int REPORT_CONFIG_SCALE_CMD_CODE = 1103;
   int WEIGHT_REQ_SCALE_CMD_CODE = 1104;
   int ZERO_SCALE_CMD_CODE = 1105;
   String CLEAR_DISPLAY_SCALE_CMD_NAME = "CLEAR_DISPLAY_SCALE_CMD";
   String CONFIG_SCALE_CMD_NAME = "CONFIG_SCALE_CMD";
   String ENABLE_EXTENDED_STATUS_CMD_NAME = "ENABLE_EXTENDED_STATUS_CMD";
   String REPORT_CONFIG_SCALE_CMD_NAME = "REPORT_CONFIG_SCALE_CMD";
   String WEIGHT_REQ_SCALE_CMD_NAME = "WEIGHT_REQ_SCALE_CMD";
   String ZERO_SCALE_CMD_NAME = "ZERO_SCALE_CMD";
   byte ScaleType4687 = 1;
   byte ScaleType4696 = 2;
   byte ScaleType4698 = 3;
}
