package com.ibm.hid;

public interface HidConst {
   byte HID_CLASS = 3;
   byte HID_GET_REPORT_REQUEST = 1;
   byte HID_GET_IDLE_REQUEST = 2;
   byte HID_GET_PROTOCOL_REQUEST = 3;
   byte HID_GET_DESCRIPTOR_REQUEST = 6;
   byte HID_SET_DESCRIPTOR_REQUEST = 7;
   byte HID_SET_REPORT_REQUEST = 9;
   byte HID_SET_IDLE_REQUEST = 10;
   byte HID_SET_PROTOCOL_REQUEST = 11;
   byte HID_GET_DESCRIPTOR_REQUESTTYPE = -127;
   byte HID_GET_REPORT_REQUESTTYPE = -95;
   byte HID_GET_IDLE_REQUESTTYPE = -95;
   byte HID_GET_PROTOCOL_REQUESTTYPE = -95;
   byte HID_SET_DESCRIPTOR_REQUESTTYPE = 1;
   byte HID_SET_REPORT_REQUESTTYPE = 33;
   byte HID_SET_IDLE_REQUESTTYPE = 33;
   byte HID_SET_PROTOCOL_REQUESTTYPE = 33;
   byte HID_DESCRIPTOR_TYPE_HID = 33;
   byte HID_DESCRIPTOR_TYPE_REPORT = 34;
   byte HID_DESCRIPTOR_TYPE_PHYSICAL = 35;
   byte HID_REPORT_TYPE_INPUT = 1;
   byte HID_REPORT_TYPE_OUTPUT = 2;
   byte HID_REPORT_TYPE_FEATURE = 3;
   byte HID_PROTOCOL_TYPE_BOOT = 0;
   byte HID_PROTOCOL_TYPE_REPORT = 1;
   byte HID_REPORT_ID_UNUSED = 0;
   byte HID_DESCRIPTOR_INDEX_UNUSED = 0;
   short HID_USAGE_PAGE_GENERIC_DESKTOP = 1;
   short HID_USAGE_ID_KEYBOARD = 6;
}
